package it.difesa.esercito.jpwebform.aps.system.services;

import it.difesa.esercito.plugins.jpwebform.aps.system.services.sige.SigeUserHelper;
import junit.framework.TestCase;

public class TestSigeUserHelper extends TestCase {

    public void testGetEmail() {
        String email = SigeUserHelper.getUserEmail(SIGE_JSON_USER);
        assertNotNull(email);
        assertEquals("l.basi@enando.com", email);

        String fullName = SigeUserHelper.getSigeUserFullName(SIGE_JSON_USER);
        assertEquals("Sergente MAURIZIO COGNOME (BALLUA79D10F839I)", fullName);
    }

    public final static String SIGE_JSON_USER = "{\n"
            + "  \"id\": 1234567,\n"
            + "  \"firstname\": \"MAURIZIO\",\n"
            + "  \"lastname\": \"COGNOME\",\n"
            + "  \"degree\": \"Sergente\",\n"
            + "  \"active\": true,\n"
            + "  \"fiscalCode\": \"BALLUA79D10F839I\",\n"
            + "  \"email\": \"l.basi@enando.com\",\n"
            + "  \"armedForce\": \"-\",\n"
            + "  \"dateOfBirth\": \"1982-04-30\",\n"
            + "  \"phone\": \"\",\n"
            + "  \"mobilePhone\": \"\",\n"
            + "  \"city\": \"RM\",\n"
            + "  \"rawData\": {\n"
            + "    \"ammCodAmm\": \"-\",\n"
            + "    \"assunzione\": \"S\",\n"
            + "    \"categoria\": \"S\",\n"
            + "    \"codomon\": null,\n"
            + "    \"codArma\": \"-\",\n"
            + "    \"codFineServ\": null,\n"
            + "    \"codFiscale\": \"BALLUA79D10F839I\",\n"
            + "    \"codForzaAmm\": \"07\",\n"
            + "    \"codGrado\": \"EQ\",\n"
            + "    \"codGruppo\": \"-\",\n"
            + "    \"codIncarico\": \"-\",\n"
            + "    \"codLocalita\": \"G273\",\n"
            + "    \"codLocgiu\": \"-\",\n"
            + "    \"codLocimp\": \"-\",\n"
            + "    \"codOrarioPres\": \"-\",\n"
            + "    \"codPossta\": \"448\",\n"
            + "    \"codProfilo\": null,\n"
            + "    \"codRegioneMil\": \"-\",\n"
            + "    \"codRuolo\": \"-\",\n"
            + "    \"codSettore\": null,\n"
            + "    \"codSettoreArma\": \"-\",\n"
            + "    \"codStatoCivile\": \"-\",\n"
            + "    \"codTipoForza\": \"-\",\n"
            + "    \"codUnOper\": \"-\",\n"
            + "    \"codVariazPerdForza\": null,\n"
            + "    \"codVariazPresaInForza\": \"AS\",\n"
            + "    \"cognome\": \"COGNOME\",\n"
            + "    \"comuneNascita\": \"Palermo (PA)\",\n"
            + "    \"datavariaz\": null,\n"
            + "    \"denomEnteAmministrativo\": \"21033 - 11 REGGIMENTO TRASMISSIONI - CIVITAVECCHIA (RM)\",\n"
            + "    \"denomEnteAppartenenza\": \"21033 - 11 REGGIMENTO TRASMISSIONI - CIVITAVECCHIA (RM)\",\n"
            + "    \"denomEnteGiuramento\": \"-\",\n"
            + "    \"denomEnteMatricolare\": \"-\",\n"
            + "    \"denomEnteServizio\": \"21033 - 11 REGGIMENTO TRASMISSIONI - CIVITAVECCHIA (RM)\",\n"
            + "    \"denomKente\": \"-\",\n"
            + "    \"denArma\": \"-\",\n"
            + "    \"denGrado\": \"Sergente\",\n"
            + "    \"denIncarico\": \"-\",\n"
            + "    \"denPossta\": \"-\",\n"
            + "    \"denRuolo\": \"-\",\n"
            + "    \"denSettoreArma\": \"-\",\n"
            + "    \"denStatoCivile\": \"CONIUGATO/A\",\n"
            + "    \"descrizionepersonale\": \"Sottufficiali\",\n"
            + "    \"dtAmministrativa\": null,\n"
            + "    \"dtAnzSpallina\": null,\n"
            + "    \"dtAppartenenza\": null,\n"
            + "    \"dtArruol\": null,\n"
            + "    \"dtAssForza\": null,\n"
            + "    \"dtFineServ\": null,\n"
            + "    \"dtGiuramento\": null,\n"
            + "    \"dtImpianto\": null,\n"
            + "    \"dtIncorporazione\": null,\n"
            + "    \"dtInAnzGrado\": null,\n"
            + "    \"dtInIncarico\": null,\n"
            + "    \"dtMatricolare\": null,\n"
            + "    \"dtNascita\": \"1982-08-30\",\n"
            + "    \"dtPerdForza\": null,\n"
            + "    \"dtPromozione\": null,\n"
            + "    \"dtServizio\": null,\n"
            + "    \"enteAmministrativo\": \"21033\",\n"
            + "    \"enteAppartenenza\": \"21033\",\n"
            + "    \"enteGiuramento\": \"-\",\n"
            + "    \"enteMatricolare\": \"-\",\n"
            + "    \"enteServizio\": \"21033\",\n"
            + "    \"fa\": \"EI\",\n"
            + "    \"fkCodicereligione\": \"-\",\n"
            + "    \"fkCodicesuffisso\": \"-\",\n"
            + "    \"flagAttivo\": \"S\",\n"
            + "    \"flagLegge104\": \"N\",\n"
            + "    \"flagTrasf\": \"-\",\n"
            + "    \"flagTurnista\": \"N\",\n"
            + "    \"gradoLiv\": \"-\",\n"
            + "    \"idBdc\": \"BALLUA79D10F839I\",\n"
            + "    \"idLivello\": null,\n"
            + "    \"idPersMtr\": 1721558,\n"
            + "    \"idRelativoInForza\": 1,\n"
            + "    \"idRelativoPerdForza\": 93,\n"
            + "    \"impiantatoDaEnte\": \"-\",\n"
            + "    \"impiegoMatricolare\": \"-\",\n"
            + "    \"indDomicilio\": \"VIA AURELIA EST, km 18,500\",\n"
            + "    \"indResidenza\": \"VIA GIUSEPPE GARIBALDI,47\",\n"
            + "    \"kdatavari\": null,\n"
            + "    \"kdatavaru\": null,\n"
            + "    \"kente\": \"25414\",\n"
            + "    \"kutentei\": \"-\",\n"
            + "    \"kutenteu\": \"-\",\n"
            + "    \"localitaDomicilio\": \"CIVITAVECCHIA (AURELIA)\",\n"
            + "    \"localitaResidenza\": \"MISILMERI\",\n"
            + "    \"locDomicilio\": \"059501\",\n"
            + "    \"locResidenza\": \"086048\",\n"
            + "    \"matricola\": \"012345678901\",\n"
            + "    \"nome\": \"MAURIZIO\",\n"
            + "    \"numord\": null,\n"
            + "    \"numordBdc\": null,\n"
            + "    \"nFigli\": 2,\n"
            + "    \"persMant\": \"-\",\n"
            + "    \"posme\": \"-\",\n"
            + "    \"provinciaNascita\": \"PA\",\n"
            + "    \"provServ\": \"RM\",\n"
            + "    \"prDom\": \"RM\",\n"
            + "    \"prRes\": \"PA\",\n"
            + "    \"qualificaMef\": \"-\",\n"
            + "    \"regioneNascita\": \"Sicilia\",\n"
            + "    \"sesso\": \"M\",\n"
            + "    \"sigla\": \"-\",\n"
            + "    \"siglaGrado\": \"Serg.\",\n"
            + "    \"tpPers\": \"S\",\n"
            + "    \"capDomicilio\": \"00100\",\n"
            + "    \"capResidenza\": \"00100\"\n"
            + "  }\n"
            + "}";

}
