#export ENTANDO_OPT_DOCKER_USERNAME="${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}"
#export ENTANDO_OPT_DOCKER_PASSWORD="${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}"

name: CYPRESS

env: 
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "test-cypress"
  APP_NAME: "test-cypress"
  IMAGE_REGISTRY: entando/app-engine-eap:7.2.0-ENG-4504-PR-45
  IMAGE_REGISTRY_USER: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
jobs:
  openshift-deployment:
    name: Deploy application to OKD environment
    runs-on: ubuntu-latest
    steps:
    - name: Login to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Install Entando Operator
      run: |
        manifest="${{ secrets.OPENSHIFT_OPERATOR_GROUP }}"
        echo "${manifest//"{{namespace}}"/"${{ env.OPENSHIFT_NAMESPACE }}"}" > new-manifest.yaml
        oc apply -f new-manifest.yaml
        subscription_manifest="${{ secrets.OPENSHIFT_SUBSCRIPTION_MANIFEST }}"
        subscription_manifest=$"${subscription_manifest//"{{namespace}}"/"${{ env.OPENSHIFT_NAMESPACE }}"}"
        echo "${subscription_manifest//"{{source}}"/"entando-catalog-7-1-3"}" > subscription-manifest.yaml
        oc apply -f subscription-manifest.yaml
        entando_app_manifest="${{ secrets.OPENSHIFT_ENTANDO_APP_MANIFEST }}"
        entando_app_manifest=$"${entando_app_manifest//"{{namespace}}"/"${{ env.OPENSHIFT_NAMESPACE }}"}"
        entando_app_manifest=$"${entando_app_manifest//"{{dbms}}"/"postgresql"}"
        entando_app_manifest=$"${entando_app_manifest//"{{appname}}"/"${{ env.OPENSHIFT_NAMESPACE }}"}"
        entando_app_manifest=$"${entando_app_manifest//"{{appused}}"/"eap"}"
        echo "${entando_app_manifest//"{{openshift_url}}"/"okd4-10.awsentando.net"}" > entando-app-manifest.yaml
        cat entando-app-manifest.yaml
        oc apply -f entando-app-manifest.yaml
        
        
        
#namespace=test-cypress
#dbms=postgresql
#appname=test-cypress
#appused=eap
#openshift_url=okd4-10.awsentando.net

#metadata:
#  name: {{ namespace }}      #Lá tava name: entando-k8s-operator.v7.1.3
#  namespace: {{ namespace }}
#spec:
#  environmentVariables: []
#  dbms: {{ dbms }}
#  name: {{ appname }}
#  standardServerimage: {{ appused }}  
#  ingressHostName: {{ appname }}.apps.{{ openshift_url }}

#        echo "${manifest//"{{namespace}}"/"${{ env.OPENSHIFT_NAMESPACE }}"}" > new-manifest.yaml --> THIS WORKS
#        manifest=$(cat << EOF
#        first line
#        second line
#        third line
#        EOF
#        )
#        manifest="${{ secrets.OPENSHIFT_OPERATOR_GROUP }}"

#        manifest= |
#          "apiVersion: operators.coreos.com/v1
#          kind: OperatorGroup
#          metadata:
#            name: {{namespace}}
#            namespace: {{namespace}}
#          spec:
#            targetNamespaces:
#            - {{namespace}}"


#   echo "${firstString/Suzi/"$secondString"}" 
#   cat temp2.txt | oc process -f - -p namespace=test-cypress > new-manifest.yaml
#   manifest="test 123" --> This WORKS
#   manifest="${{ secrets.OPENSHIFT_OPERATOR_GROUP }}" --> This WORKS


#        echo "$manifest" | oc process -f - -p namespace=test-cypress > new-manifest.yaml
        
#    - name: Install Entando Operator 3
#      run: cat new-manifest.yaml
      #run: |
      #  manifest=$(echo ${{ secrets.OPENSHIFT_OPERATOR_GROUP }} | base64 --decode)
      #  echo "$manifest" | oc process -f - -p NAMESPACE=my-namespace > new-manifest.yaml
      #  cat new-manifest.yaml