name: CYPRESS

env: 
  JOB_CONFIGURATION_TOKEN: ${{ secrets.JOB_CONFIGURATION_TOKEN }}
  OPENSHIFT_DOMAIN: ${{ secrets.OPENSHIFT_DOMAIN }}
  OPENSHIFT_SERVER_PORT: ${{ secrets.OPENSHIFT_SERVER_PORT }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  ENTANDO_OPERATOR_SOURCE: "entando-catalog-7-1-3"
  ENTANDO_APP_DBMS: "postgresql"
  ENTANDO_APP_USED: "eap"
  IMAGE_REGISTRY: entando/app-engine-eap:7.2.0-ENG-4504-PR-45
  IMAGE_REGISTRY_USER: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}
  NAMESPACE: "test-cypress"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
jobs:
  prepare-namespace:
    name: Prepare namespace
    runs-on: ubuntu-latest
    steps:
    - name: Login to OpenShift with JobConfiguration
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://api.${{ env.OPENSHIFT_DOMAIN }}:${{ env.OPENSHIFT_SERVER_PORT }}
        openshift_token: ${{ env.JOB_CONFIGURATION_TOKEN }}
        insecure_skip_tls_verify: true
    - name: Create namespace
      run: oc create namespace ${{ env.NAMESPACE }}
    - name: Create ServiceAccount
      run: |
        service_account_manifest="${{ secrets.SERVICE_ACCOUNT_MANIFEST }}"
        echo "${service_account_manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}" > service-account-manifest.yaml
        oc apply -f service-account-manifest.yaml
    - name: Create Role
      run: |
        role_manifest="${{ secrets.ROLE_MANIFEST }}"
        echo "${role_manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}" > role-manifest.yaml
        oc apply -f role-manifest.yaml
    - name: Create RoleBinding
      run: |
        role_binding_manifest="${{ secrets.ROLE_BINDING_MANIFEST }}"
        echo "${role_binding_manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}" > role-binding-manifest.yaml
        oc apply -f role-binding-manifest.yaml
  install-entando-app:
    name: Install EntandoApp
    runs-on: ubuntu-latest
    needs: prepare-namespace
    steps:
    - name: Set environment variable with the new ServiceAccount token
      run: | 
        secretName = $(oc get serviceaccount ${{ env.NAMESPACE }} -n ${{ env.NAMESPACE }} -o jsonpath='{.secrets[1].name}')
        echo $secretName
        token = $(oc get secret $secretName -n ${{ env.NAMESPACE }} -o jsonpath='{.data.token}' | base64 --decode)
        echo $token
    - name: Login to OpenShift with new ServiceAccount
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://api.${{ env.OPENSHIFT_DOMAIN }}:${{ env.OPENSHIFT_SERVER_PORT }}
        #openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        openshift_token: ${{ env.JOB_CONFIGURATION_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.NAMESPACE }}
    - name: Creating Operator Group
      run: |
        manifest="${{ secrets.OPENSHIFT_OPERATOR_GROUP }}"
        echo "${manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}" > operator-group-manifest.yaml
        oc apply -f operator-group-manifest.yaml
    - name: Instaling Operator
      run: |
        subscription_manifest="${{ secrets.OPENSHIFT_SUBSCRIPTION_MANIFEST }}"
        subscription_manifest=$"${subscription_manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}"
        echo "${subscription_manifest//"{{source}}"/"${{ env.ENTANDO_OPERATOR_SOURCE }}"}" > subscription-manifest.yaml
        oc apply -f subscription-manifest.yaml
    - name: Installing EntandoApp
      run: |
        entando_app_manifest="${{ secrets.OPENSHIFT_ENTANDO_APP_MANIFEST }}"
        entando_app_manifest=$"${entando_app_manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}"
        entando_app_manifest=$"${entando_app_manifest//"{{dbms}}"/"${{ env.ENTANDO_APP_DBMS }}"}"
        entando_app_manifest=$"${entando_app_manifest//"{{appname}}"/"${{ env.NAMESPACE }}"}"
        entando_app_manifest=$"${entando_app_manifest//"{{appused}}"/"${{ env.ENTANDO_APP_USED }}"}"
        echo "${entando_app_manifest//"{{openshift_url}}"/"okd4-10.awsentando.net"}" > entando-app-manifest.yaml
        oc apply -f entando-app-manifest.yaml
  delete-namespace:
    name: Delete namespace
    runs-on: ubuntu-latest
    needs: install-entando-app
    if: always()
    steps:
    - name: Login to OpenShift with JobConfiguration
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://api.${{ env.OPENSHIFT_DOMAIN }}:${{ env.OPENSHIFT_SERVER_PORT }}
        openshift_token: ${{ env.JOB_CONFIGURATION_TOKEN }}
        insecure_skip_tls_verify: true
    - name: Delete namespace
      run: oc delete namespace ${{ env.NAMESPACE }}