#export ENTANDO_OPT_DOCKER_USERNAME="${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}"
#export ENTANDO_OPT_DOCKER_PASSWORD="${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}"

name: CYPRESS

env: 
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "test-cypress"
  APP_NAME: "test-cypress"
  IMAGE_REGISTRY: entando/app-engine-eap:7.2.0-ENG-4504-PR-45
  IMAGE_REGISTRY_USER: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
jobs:
  openshift-deployment:
    name: Deploy application to OKD environment
    runs-on: ubuntu-latest
    steps:
    - name: Login to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Install Entando Operator
      run: |
        echo "message1"
        manifest=$(cat << EOF
        apiVersion: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: {{namespace}}
          namespace: {{namespace}}
        spec:
          targetNamespaces:
          - {{namespace}}
        EOF
        )
        echo "message2"
        echo "the value of manifest is $manifest"
        echo "message3"
        echo "This is a temporary file" > temp.txt
        echo "message4"
        cat temp.txt
        echo "message5"
        echo "$manifest" > temp2.txt
        echo "message6"
        cat temp2.txt
        echo "message7"
        echo "${manifest/{{namespace}}/"${{ env.OPENSHIFT_SERVER }}"}" > new-manifest.yaml
        echo "message8"
        cat new-manifest.yaml
        echo "message9"


#        manifest=$(cat << EOF
#        first line
#        second line
#        third line
#        EOF
#        )
#        manifest="${{ secrets.OPENSHIFT_OPERATOR_GROUP }}"

#        manifest= |
#          "apiVersion: operators.coreos.com/v1
#          kind: OperatorGroup
#          metadata:
#            name: {{namespace}}
#            namespace: {{namespace}}
#          spec:
#            targetNamespaces:
#            - {{namespace}}"


#   echo "${firstString/Suzi/"$secondString"}" 
#   cat temp2.txt | oc process -f - -p namespace=test-cypress > new-manifest.yaml
#   manifest="test 123" --> This WORKS
#   manifest="${{ secrets.OPENSHIFT_OPERATOR_GROUP }}" --> This WORKS


#        echo "$manifest" | oc process -f - -p namespace=test-cypress > new-manifest.yaml
        
#    - name: Install Entando Operator 3
#      run: cat new-manifest.yaml
      #run: |
      #  manifest=$(echo ${{ secrets.OPENSHIFT_OPERATOR_GROUP }} | base64 --decode)
      #  echo "$manifest" | oc process -f - -p NAMESPACE=my-namespace > new-manifest.yaml
      #  cat new-manifest.yaml