name: CYPRESS

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
jobs:
  download-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker/setup-docker-action@v2
      - name: Pull image
        run: docker pull entando/app-engine-eap:7.2.0-ENG-4504-PR-45
